category:
    resource: "@BlogAdminBundle/Controller/CategoryController.php"
    type:     annotation

post:
    resource: "@BlogAdminBundle/Controller/PostController.php"
    type:     annotation

link:
    resource: "@BlogAdminBundle/Controller/LinkController.php"
    type:     annotation

update:
    resource: "@BlogAdminBundle/Controller/UpdateController.php"
    type:     annotation