<?php

namespace Blog\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateRepository extends EntityRepository
{
}
