listing:
    resource: "@BlogMainBundle/Controller/ListingController.php"
    type:     annotation

category:
    resource: "@BlogMainBundle/Controller/CategoryController.php"
    type:     annotation

post:
    resource: "@BlogMainBundle/Controller/PostController.php"
    type:     annotation