services:
    blog_main.service.post:
        class:     Blog\MainBundle\Service\PostService
        arguments: ["@doctrine.orm.entity_manager", "@blog_main.repository.post", "@security.context"]

    blog_main.repository.post:
        class:           Blog\MainBundle\Entity\PostRepository
        arguments:       [Blog\MainBundle\Entity\Post]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository


    blog_main.service.category:
        class:     Blog\MainBundle\Service\CategoryService
        arguments: ["@doctrine.orm.entity_manager", "@blog_main.repository.category", "@security.context"]

    blog_main.repository.category:
        class:           Blog\MainBundle\Entity\CategoryRepository
        arguments:       [Blog\MainBundle\Entity\Category]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository